name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/xfalcox/speedtest-cli/speedtest-cli:latest
    - name: Push the Docker image
      run: docker login docker.pkg.github.com -u xfalcox -p ${{ secrets.token }} && docker push docker.pkg.github.com/xfalcox/speedtest-cli/speedtest-cli:latest